### PR TITLE
Add function support for Get/Set/Reset AnimationOveride

### PR DESCRIPTION
**Pull request by mdickson**
Add function call support for animation overide functions on the server,

### CODE REVIEW

**Comment by zauberparacelsus** [comment]
Would it be possible to add a linked variant of llSetAnimationOverride, since IW has linked animation functions?  (IE: iwStartLinkAnimation and iwStopLinkAnimation).

A linked version of llGetAnimationOverride would need more thought.  Either it would return a list containing the animation and the link number it is in, or you would need to specify the link it would be checking for.

**Comment by mdickson** [comment]
I'm not sure how the linked versions would be different.  The normal script functions should be callable from any link in a linkset and function.  That is they aren't limited at least in description to the root prim,  In fact when I started looking at this I made the assumption that this applied to attachments but it may work even when sitting or via any mechanism where you can acquire the required permissions,  so I need to test a bit to verify correct behaviour.

**Comment by zauberparacelsus** [comment]
Linked versions would, like iwStartLinkAnimation and iwStopLinkAnimation, look for animations in a separate prim specified by link number instead of whatever prim the script is sitting in.

EazySeat, for example, can have multiple seats in the same linkset, but with all the animations in the root prim instead of being duplicated in each individual seat.

**Comment by appurist** [comment]
The various InWorldz-specific Link variants were inventory-related extensions that I added to remove the requirement for task inventory items to be in the same prim as the script. The most important one, especially in the context of these new functions, was probably [iwStartLinkAnimation](http://wiki.inworldz.com/izwiki/index.php/IwStartLinkAnimation) which in this case would correspond to
`void llSetAnimationOverride(string anim_state, string anim);`
I think that's the only one that would need a Link variant to complete the set, and it would be something like
`void iwSetLinkAnimationOverride(integer linknum, string anim_state, string anim);`

The only difference is that it would allow the caller to either specify the animation (specified by the final parameter) in a different prim. e.g. it could then pass that here as iwSetLinkAnimationOverride(LINK_ROOT, "Standing", name) and use the animation from another prim, different than the one the script is in.

The main benefit of these functions is to allow the root prim to host the user-visible items like user-configurable animations or textures, while placing the scripts in a "more hidden" secondary prim Contents.  It makes cases where users delete the wrong thing much less common.

**Comment by appurist** [comment]
I should add, the commit looks good to me. Ready for merge.

**Comment by appurist** [comment]
I'll merge it and build update Phlox binaries on the build machine for the Halcyon project.

**Pull request merged**
